export const GET_BRAND_LIST="GET_BRAND_LIST"
export const GET_MAKE_LIST="GET_MAKE_LIST"
export const GET_INFO_AND="GET_INFO_AND"


export const GET_LOCATION="GET_LOCATON"
export const GET_DEALER_LIST="GET_DEALER_LIST"

export const SET_FALG="SET_FALG"

export const GET_CITY_LIST="GET_CITY_LIST"
export const GET_CITY_TWO_LIST="GET_CITY_TWO_LIST"
export const SET_LOCATION="SET_LOCATION"